### ISSUE TITLE
CRAN data gets out of date

### ISSUE THREAD

**Issue by sfirke** [sfirke/packagemetrics#27]
`package_list_metrics("dplyr")` indicates that dplyr was published 2016-06-24, which is true ... for version 0.5.0.    You can see that the `cran` data object in packagemetrics is out of date on this one:

`cran %>% filter(package == "dplyr") %>% View`

Should be 0.7.0 published this month.

What's the best fix here?  Only ideas I have are:

1. We manually update and push new data ~monthly.  But then people who don't reinstall will have outdated CRAN data.
2. Could the package itself somehow check how old its CRAN data is, and if it's more than a certain age, update its own CRAN data?

**Comment by sfirke** [comment]
Ooh I forgot we have a function called `refresh_cran_database` - the question above remains, but it'll be less work no matter what direction we go in :)

**Comment by bzkrouse** [comment]
Good catch! Another option could be to throw in an optional argument to refresh in the functions that return cran metrics.

**Comment by MilesMcBain** [comment]
Could be a different approach to this problem: https://github.com/jimhester/autoinst/blob/master/R/package.R#L40

Is there any shame in hitting the RStudio CRAN mirror this way if they are doing it themselves?

**Comment by sfirke** [comment]
Closed with #33
