### ISSUE TITLE
Some GitHub URLs are wrong

### ISSUE THREAD

**Issue by csgillespie** [sfirke/packagemetrics#28]
The associated github repo of https://cran.r-project.org/web/packages/RcppDL/index.html gives a 404. Which causes

```{r}
R> scrape_github_package_page("RcppDL")
Error in open.connection(x, "rb") : HTTP error 404.
```

Suggestion: Use `httr::GET` to retrieve the page. If bad, return NA, otherwise pass the context to `xml2`

**Comment by sfirke** [comment]
hey look, you closed this yourself with #33.  Thanks @csgillespie, I added you to the description of this package as a contributor.
