### ISSUE TITLE
installation fails with install_github

### ISSUE THREAD

**Issue by sfirke** [sfirke/packagemetrics#38]
I'm on Windows 10, is this a problem for others?
```
devtools::install_github("ropenscilabs/packagemetrics")
Downloading GitHub repo ropenscilabs/packagemetrics@master
from URL https://api.github.com/repos/ropenscilabs/packagemetrics/zipball/master
Installing packagemetrics
Installation failed: missing value where TRUE/FALSE needed
```
Trying to use our package to compare `sjlabelled`, `labelled`, and `labelVector`.  As a control, I can successfully install the `skimr` package from ropenscilabs on GitHub.

**Comment by hfrick** [comment]
Same on Mac

**Comment by sfirke** [comment]
Might be related to: https://community.rstudio.com/t/library-tidyverse-results-in-error-on-r-studio/2642/23  As I seem to be able to install with regular R, not RStudio??

**Comment by csgillespie** [comment]
Works for me

**Comment by sfirke** [comment]
I can no longer reproduce this, it installs successfully.
