### ISSUE TITLE
Link in https://ropensci.org/blog/2017/06/27/packagemetrics/ to review of table packages is broken

### ISSUE THREAD

**Issue by AndreaPi** [sfirke/packagemetrics#44]
Hi!

As per subject, the link in the [packagemetrics blog post](https://ropensci.org/blog/2017/06/27/packagemetrics/) to the page with the start of a review of a selection of table-making packages is [broken](http://htmlpreview.github.io/?https://github.com/ropenscilabs/packagemetrics/blob/master/inst/doc/tableGallery.html). The correct link should be [this one](https://htmlpreview.github.io/?https://github.com/ropenscilabs/packagemetrics/blob/master/inst/examples/tableGallery.html). Can you fix the link in the blog post? Thanks!

**Comment by hfrick** [comment]
thanks for the heads-up! I've submitted a PR to fix it

**Comment by hfrick** [comment]
and merged :)
