### ISSUE TITLE
date of release

### ISSUE THREAD

**Issue by eringrand** [sfirke/packagemetrics#5]
Can we get the date of latest release versus the first release

**Comment by sfirke** [comment]
I think this is currently coming through under the "published" column.  E.g., dplyr shows 2016-06-24 which is the release date for the "latest" 0.5.0 release.  Now of course dplyr is now on 0.7.1 which begs the question, is there a way for the `cran` data.frame to automatically update itself periodically?  I'll open as a new issue.
