### ISSUE TITLE
problem with mutate

### ISSUE THREAD

**Issue by verajosemanuel** [sfirke/packagemetrics#59]
```
packages_list <- c("renv","packagemetrics")
packagemetrics::package_list_metrics(packages_list)

Error: Problem with `mutate()` input `action`.
x Input `action` can't be recycled to size 2.
i Input `action` is `c("watchers", "stars", "forks")`.
i Input `action` must be size 2 or 1, not 3.
```

**Comment by timtreis** [comment]
Same error

![image](https://user-images.githubusercontent.com/12818242/120935264-2d5f1480-c702-11eb-8b63-4d8e1b64e625.png)

**Comment by sfirke** [comment]
Thanks for reporting this!  It appears that now GitHub does not show you the "watchers" count if you're not logged in.  So the scraper is only able to get the counts of stars and forks.  I've adjusted that code accordingly.  If you are able to reinstall `packagemetrics` from GitHub and re-try, I'd appreciate it.  And if I broke anything else or did not solve this, please open another issue.
